project_id = "hannairmzwhlurkwydph"

[functions.public-restaurant]
verify_jwt = false

[functions.public-order]
verify_jwt = false

[functions.public-booking]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true
